app = "jawwalpay-cache-service"

[build]
  image = "" # optional: Fly can build from Dockerfile by default

[env]
  PORT = "3000"
  DB_PATH = "/data/data.json"

[[mounts]]
  source = "backend-data"
  destination = "/data"
